---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes' 
summary: Descubra las novedades sobre el almacenamiento de Amazon S3 en la NetApp Console. 
---
= Novedades del almacenamiento de Amazon S3 en la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Descubra las novedades sobre el almacenamiento de Amazon S3 en la NetApp Console.



== 6 de octubre de 2025



=== BlueXP ahora es NetApp Console

La NetApp Console, construida sobre la base BlueXP mejorada y reestructurada, proporciona una gestión centralizada del almacenamiento de NetApp y de los NetApp Data Services en entornos locales y en la nube a nivel empresarial, brindando información en tiempo real, flujos de trabajo más rápidos y una administración simplificada, que es altamente segura y compatible.

Para obtener más detalles sobre lo que ha cambiado, consulte lalink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Notas de la versión de la NetApp Console"] .



== 5 de marzo de 2023



=== Capacidad de agregar nuevos depósitos desde BlueXP

Ha tenido la capacidad de ver los buckets de Amazon S3 en BlueXP Canvas durante bastante tiempo.  Ahora puede agregar nuevos depósitos y cambiar las propiedades de los depósitos existentes directamente desde BlueXP. https://docs.netapp.com/us-en/storage-management-s3-storage/task-add-s3-bucket.html["Vea cómo agregar nuevos buckets de Amazon S3"] .
